version: "3"

services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /src:/src
      - /config:/config
    environment:
      - POSTGRES_HOST=auth
      - POSTGRES_POSRT=5433
      - POSTGRES_USER=postgres
      - POSTGRS_PSWD=postgres
      - POSTGRES_DB=users
    depends_on:
      - auth_db
  auth_db:
    container_name: auth_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    ports:
      - 5433:5432
    volumes:
      - ./db-data:/usr/app/data
